spring.profiles.active=@spring.profiles.active@

server.port=8083

spring.application.name=stripe-provider-service

management.endpoints.web.exposure.include=*
management.info.env.enabled=true

info.app.name=${spring.application.name}
info.app.version=1.0.0
info.app.description=Microservice for stripe provider service. Integrates with Stripe API to create payment sessions and handle payment processing.