mytestkey=This value is from LOCAL properties file


stripe.api.key=${STRIPE_API_KEY}

stripe.create.session.url=https://api.stripe.com/v1/checkout/sessions



# ========= Eureka Client Configuration =========
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}

stripe.webhook.endpoint-secret=${STRIPE_NOTIFICATION_SECRET}