#spring.profiles.active=@spring.profiles.active@
spring.profiles.active=local

server.port=8081

spring.application.name=payment-validation-service

# Connect to Config Server - currently commented out for local development,
# spring.config.import=configserver:http://localhost:8888


# Enable Circuit Breaker metrics in Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.enabled=true
management.health.circuitbreakers.enabled=true
 
management.endpoint.health.show-details=always

management.info.env.enabled=true

info.app.name=payment-validation-service
info.app.version=1.0.0
info.app.description=Spring Boot Microservice for Payments validation service. Field & Business validation
