server.port=8888

spring.application.name=payment-config-server

#spring.profiles.active=native

# my properties configuration is classpath /config location
#spring.cloud.config.server.native.searchLocations=classpath:/config

# read the config files from local file system D:\ctws\feb26ct\config
#spring.cloud.config.server.native.searchLocations=file:///D:/ctws/feb26ct/config

# Enable Git backend
spring.cloud.config.server.git.uri=https://tausiefs@bitbucket.org/careertransformation/payment-config-properties-feb26ct.git

# Branch (important)
spring.cloud.config.server.git.default-label=main

spring.cloud.config.server.git.username=tausiefs
spring.cloud.config.server.git.password=${BITBUCKET_API_TOKEN_READ_REPO}
